version: "3.7"
services: 

  db:
    image: mariadb:10
    container_name: wp-60sec-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
  
  wordpress-fpm:
    image: wordpress:5-fpm-alpine
    container_name: wp-60sec-fpm
    links:
      - db
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
  
  nginx:
    image: nginx:alpine
    container_name: wp-60sec-nginx
    depends_on: 
      - wordpress-fpm
    ports:
      - 8085:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wp_files:/var/www/html

volumes: 
  wp_files: 
